Add the Phonex algorithm.
Dalvany/rphonetic pull request #33
Opened 2023-05-09 22:34 UTC by antzucaro

Add the `phonex` algorithm, which is a modification of Soundex by A. J. Lait and B. Randell from their paper "[An Assessment of Name Matching Algorithms](https://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=E3997DC51F2046A95EE6459F2B997029?doi=10.1.1.453.4046&rep=rep1&type=pdf)".

I don't know Rust very well, so I stuck to the "shape" of the other algorithms found in this repo. Cheers!

2023-05-10 18:57 UTC, Dalvany commented
Hi, thanks for the contribution !
I'll look into the pull request by the end of the week !

2023-05-10 19:19 UTC, Dalvany requested changes

2023-05-10 19:19 UTC, Dalvany commented on src/phonex.rs
> +/// paper "An assessment of name matching algorithms" in the Technical Report
I add the link to the paper in documentation, if anyone want to read it.
```suggestion
/// paper ["An assessment of name matching algorithms"](https://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=E3997DC51F2046A95EE6459F2B997029?doi=10.1.1.453.4046&rep=rep1&type=pdf) in the Technical Report
```

2023-05-10 19:19 UTC, Dalvany commented on src/phonex.rs
> +/// paper "An assessment of name matching algorithms" in the Technical Report
I'll directely commit suggestion and it's good !

2023-05-10 19:28 UTC, Dalvany approved these changes

2023-05-10 19:29 UTC, Dalvany commented
Unfortunately, clippy workflow was disabled. I'll merge the pull request anyway

2023-05-10 19:29 UTC, merged

2023-05-10 19:30 UTC, Dalvany commented
I'll let clippy run on main branch and make a new version. Thanks again for adding the algorithm !

2023-05-10 19:58 UTC, Dalvany commented
I made a few changes, some from clippy linter, and I saw we can switch some comparison from string to char (see this [commit](https://github.com/Dalvany/rphonetic/commit/00e1915556a92b51739222b957ae38f284ad06b1))
I believe we can even improve since it's only ASCII characters we do not need the `chars()` call, it will also be more consistent with the replace_range call that works only because we're using ASCII.
I should check my own code for the non clippy change I made here.

2023-05-10 20:26 UTC, Dalvany commented
Released version [2.0.0](https://crates.io/crates/rphonetic)

2023-05-10 22:24 UTC, Dalvany commented
I also made another change, when encoding only number, it returns an empty string instead of a code consisting only of '0', like soundex and other algorithm.

2023-05-11 17:36 UTC, antzucaro commented
Thanks @Dalvany ! Agree w/ the replacement of `chars()` - that makes sense. Let me know how I can help there. I will also take a look around for other similar algorithms from some scholarly resources I have.

2023-05-11 17:37 UTC, antzucaro commented
On the all zeros change for numerical input, I can check with the original code. If it differs from the C implementation then we should put a notice in the docs about it. In all likelihood it was an oversight on my end, though!

2023-05-11 18:37 UTC, Dalvany commented
I'll be glad to add any other algorithm you might have !

Let me know about the zeros, it's just that I use this crate in another one (tantivy-analysis-contrib that brings to [Tantivy](https://github.com/quickwit-oss/tantivy) some of [Lucene](https://lucene.apache.org/core/)'s analysis components).
I started making changes to add phonex and there's a [test that tries to convert numerical values](https://github.com/Dalvany/tantivy-analysis-contrib/blob/main/src/phonetic/generic.rs#L870) for some algorithm and check that we get the same number as output (it means in the context of the test, that the underlying algorithm returns an empty string). Since soundex was amongst them and  you said phonex was an improvement, I assumed that it should behave the same, hence the change I made.
If you confirm that it outputs `0s`, I'll try to handle things into my tantivy's analysis crate. In case do you think that getting only 0s means that the input string can't be converted ? If so it will be simple to handle this special case in tantivy and keep the original phonex here.

2023-05-12 13:33 UTC, antzucaro commented
Zero padding is there in the original C implementation, so it was a bug in my porting. What's more is that the first character is copied as-is. For example, `12345` -> `10000`.

2023-05-12 17:23 UTC, Dalvany commented
If zero padding is in original C code, it's my modification that disabled it, I'll revert to match C implementation and deal with this case in my tantivy filter.
Do you think you could try to solve the first character issue ?

2023-05-12 17:30 UTC, antzucaro commented
I will work on first character issue. I now have a test harness w/ the C implementation for getting accurate values that we can put into the tests.

2023-05-12 18:55 UTC, Dalvany commented
[Here](https://github.com/Dalvany/rphonetic/pull/37) the pull request that revert my changes about encoding a string that have only numbers or is empty.

2023-05-12 20:24 UTC, Dalvany commented
And [here](https://github.com/Dalvany/rphonetic/pull/39) encode improvement if you want to take a look at it.
There's still something that I don't understand because my attempt to remove the `else` fails and I don't get why (see the whole comment that contains the TODO).